version: 1.0.0.{build}
skip_tags: true
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: cBbjHgg5rQjFgwAjjQGUFwhESw5oEljRFzESN+/xmH8vKXg3AzfVlexOpi0EBaKN
  SonarQube_Token:
    secure: 4SAyRqYsx6khVu6ERCwz3arpWEuZ82ZEDGRdTbZSfKCk5vtx4zxLc3QWcquAsC0x
install:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

    .paket\paket.bootstrapper.exe

    .paket\paket.exe restore
build:
  verbosity: minimal
after_build:
- cmd: >-
    .paket\paket.exe pack output nupkgs
after_test:
- cmd: .\run_coverage.cmd
- cmd: .\run_quality.cmd